# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ac1018f4ad6211b3a0494e748d62ae4d4129343adcc311f9929bd17d12425bc4682d9160f43b31e671204192f5b2b7bad6f8522b293475f7c016f58513a3820

test:
  secret_key_base: 506a8ce203152b663ac2202b6a2f4a9a8182039738fb93074608a1f3644d7b77ba8ae64cce9056123029ccc4e51821bb773c653b8314916e8fbb9af29c38f7c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
